#Numpy


In [ ]:
import numpy as np

#Numpy Arrays
1) Vectors - 1D Arrays
2) Matrices - 2D Arrays

In [ ]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

To convert the above python list into numpy array, use **np.array(my_list)**

In [ ]:
np.array(my_list)

array([1, 2, 3, 4, 5])

In [ ]:
type(np.array(my_list))

numpy.ndarray

We can also create 2 or multi dimensional array

In [ ]:
s = [[1,2,3],[4,5,6],[7,8,9]]
np.array(s)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
type(np.array(s))

numpy.ndarray

#Built in Methods
1) arange - array of range
2) Zeros - array of zeros
3) Ones - array of ones
4) Linspace - return evenly spaced numbers
5) eye - returns a 2D array with 1s at diagonals and remaining places with 0
6) Random - returns random values in given shape with random samples

##Arange

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(56,100,5)

array([56, 61, 66, 71, 76, 81, 86, 91, 96])

##Zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.zeros((10,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Initally the datatype will be float, we can also convert datatype using below method

In [ ]:
np.zeros((10,5), dtype = int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

##Ones

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##Linspace

In [ ]:
np.linspace(0,2)

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

We can also evenly divide according to user needs by giving how many values as third argument

In [ ]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

##Eye

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

##Random

In [ ]:
np.random.rand(5) #uniform distribution

array([0.37902774, 0.37171503, 0.19479067, 0.47658972, 0.09382893])

In [ ]:
np.random.rand(5,4)

array([[0.12354737, 0.64721801, 0.77664323, 0.62748681],
       [0.52713501, 0.26042823, 0.72824145, 0.28907846],
       [0.9724889 , 0.96696758, 0.00911817, 0.46233629],
       [0.57294297, 0.02234412, 0.44161279, 0.21108004],
       [0.05961968, 0.29523006, 0.36917636, 0.25399296]])

In [ ]:
np.random.rand(5,5,7)

array([[[0.7878726 , 0.36556661, 0.86208968, 0.05158515, 0.0591433 ,
         0.47869353, 0.79128591],
        [0.006544  , 0.55107642, 0.11933119, 0.75513393, 0.93788429,
         0.5332406 , 0.91035828],
        [0.82774704, 0.35160054, 0.08918259, 0.03901952, 0.68498355,
         0.03058321, 0.55228765],
        [0.40516783, 0.76452256, 0.71207414, 0.10223348, 0.55052898,
         0.99438464, 0.88296401],
        [0.98755819, 0.44882125, 0.64993964, 0.90162581, 0.2788075 ,
         0.01958995, 0.86304284]],

       [[0.62977729, 0.21621147, 0.45974637, 0.03396187, 0.80572802,
         0.79351976, 0.0052301 ],
        [0.82115637, 0.43458302, 0.01801728, 0.56958441, 0.196567  ,
         0.31988767, 0.6147961 ],
        [0.26695281, 0.23952153, 0.29588356, 0.57482438, 0.51098277,
         0.18817399, 0.69135628],
        [0.80983788, 0.05217228, 0.65156075, 0.48548114, 0.43416473,
         0.68182167, 0.56520147],
        [0.98907128, 0.01978058, 0.20971966, 0.41048074, 0.49247166,
  

In [ ]:
np.random.randn(5) #normal distribution

array([ 0.206282  , -0.8151334 ,  2.11054569, -0.70581584,  0.19602535])

In [ ]:
np.random.randn(1,100)

array([[ 0.20760046, -1.58086904, -0.83633792,  1.07660806,  0.37336737,
        -1.19147842,  0.91575055,  0.24301163,  1.2867496 ,  1.88160702,
        -0.45129119, -0.11816096, -0.66104275,  0.68020561, -0.60589947,
        -0.41681297,  1.11959447, -1.66951432,  0.44366577, -0.14275389,
        -0.42163083, -0.78567455,  0.08159577, -0.09998716, -0.95776123,
        -0.72039796, -2.30101721, -0.74116833,  0.14739   , -0.40162131,
        -0.98851574,  0.62063464,  0.401329  , -1.44054341,  1.14273092,
        -0.19978706,  1.52196827, -0.56906572, -1.45793906,  1.1998696 ,
        -0.82858979,  1.42671464, -0.68946653,  0.76523847, -0.66634146,
        -0.79875162,  0.45959376,  0.6199812 ,  1.94492669,  2.42868877,
        -0.38880852,  0.39359275, -0.0970257 , -0.04113574,  1.0549364 ,
        -0.22113005, -0.08161918, -0.19870058,  1.90665083, -0.63312979,
        -0.16162081, -0.79987189,  2.14343516,  1.04311685,  0.72456236,
        -1.52984172, -0.6222724 , -0.61078329, -0.1

In [ ]:
np.random.randint(100)

20

In [ ]:
np.random.randint(1,100)

74

In [ ]:
np.random.randint(1,100,6)

array([79, 38, 15, 57, 81, 35])

#Array Attributes and Methods
1) reshape
2) min()
3) Max()
4) argmin()
5) argmax()
6) shape

In [ ]:
ar = np.arange(25)

In [ ]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
nar = np.random.randint(0,50,10)

In [ ]:
nar

array([37,  6, 36,  1,  0, 26, 37, 21, 48, 49])

In [ ]:
ar.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
nar.min()

0

In [ ]:
nar.max()

49

In [ ]:
nar.argmax()

9

In [ ]:
nar.argmin()

4

In [ ]:
ar.shape

(25,)

In [ ]:
c = ar.reshape(5,5)

In [ ]:
c.shape

(5, 5)

In [ ]:
ar.dtype

dtype('int64')

#Numpy Indexing and Selection

In [ ]:
ar = np.arange(10)

In [ ]:
ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##Bracket Indexing

In [ ]:
ar[6]

6

In [ ]:
ar[1:7:2]

array([1, 3, 5])

## BroadCasting

In [ ]:
ar[0:5] = 3

In [ ]:
ar

array([3, 3, 3, 3, 3, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(0,10)

In [ ]:
slice_arr = arr[0:5]

In [ ]:
slice_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_arr[:] = 99

In [ ]:
slice_arr #This slice_arr variable will also have effect in original array whih is arr

array([99, 99, 99, 99, 99])

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9])

### Before performing any operations like indexing, we need to create a copy of the original array by using array.copy() method. This is happening because there won't be new memory created by python for performing operations in arrays

In [ ]:
asd = np.arange(10,20)

In [ ]:
asd

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
asd_copy = asd.copy()

In [ ]:
slice_asd_copy = asd_copy[1:5]
slice_asd_copy

array([11, 12, 13, 14])

In [ ]:
slice_asd_copy[:] = 24
slice_asd_copy

array([24, 24, 24, 24])

In [ ]:
print(asd)
print(asd_copy)
print(slice_asd_copy)

[10 11 12 13 14 15 16 17 18 19]
[10 24 24 24 24 15 16 17 18 19]
[24 24 24 24]


##Indexing on 2D array
SYNTAX : arr_2d[row][col] or arr_2d[row,col]

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr_2d[1] #indexing

array([4, 5, 6])

In [ ]:
arr_2d[0][1] #indexing

2

In [ ]:
arr_2d[:2] #slicing

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_2d[:2,1] #slicing

array([2, 5])

In [ ]:
arr_2d[:2,1:] #slicing

array([[2, 3],
       [5, 6]])

##Fancy Indexing

In [28]:
arr2 = np.zeros((10,7))
arr2

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [32]:
arr2_length = arr2.shape[1]
arr2_length

7

In [33]:
for i in range(arr2_length):
  arr2[i] = i

In [34]:
arr2

array([[0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9.]])

In [35]:
arr2[[2,5,8]] #Fancy indexing

array([[2., 2., 2., 2., 2., 2., 2.],
       [5., 5., 5., 5., 5., 5., 5.],
       [8., 8., 8., 8., 8., 8., 8.]])

#Selection

In [36]:
arg = np.arange(18)

In [37]:
arg>8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [39]:
bool_arg = arg>8
bool_arg

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [40]:
arg[bool_arg]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17])

In [41]:
arg[arg>9]

array([10, 11, 12, 13, 14, 15, 16, 17])

#Numpy Operations

In [42]:
a = np.arange(0,10)

In [43]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
a/a

<ipython-input-45-18210b5178b0>:1: RuntimeWarning: invalid value encountered in divide
  a/a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [46]:
0/0

ZeroDivisionError: division by zero

#Universal Array Functions

In [48]:
np.sqrt(arr_2d)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [49]:
np.exp(arr_2d)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [50]:
np.log(arr_2d)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [51]:
np.sin(arr_2d)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])